import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillInstagram, AiFillLinkedin} from "react-icons/ai";
import avatar from '../public/profile.png';
import design from '../public/design.png';
import code from '../public/code.png';
import camera from '../public/camera.png';
import web1 from '../public/webnew1.jpg';
import web2 from '../public/webnew2.jpg';
import web3 from '../public/webnew3.jpg';
import web4 from '../public/webnew4.jpg';
import Link from 'next/link'
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dinan Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 scroll-smooth">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-black text-2xl font-burtons dark:text-white">dinannn</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="fill-black cursor-pointer text-2xl dark:fill-white" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 px-2 rounded-md ml-8 font-medium" href="#projects">Projects</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">

          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Muhammad Dinan</h2>
          <h3 className="text-black text-2xl py-2 dark:text-white md:text-3xl">Tech Nerd.</h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto">Programming & Photography Enthusiast.</p>

          </div>
          <div className="text-5xl flex justify-center gap-16 py-2 text-gray-600 dark:text-gray-400">

          <a target="_blank" href="https://github.com/dxlgnds" rel="noopener noreferrer"><AiFillGithub/></a>
          <a target="_blank" href="https://linkedin.com/in/muhammad-dinan" rel="noopener noreferrer"><AiFillLinkedin/></a>
          <a target="_blank" href="https://instagram.com/frkdinan" rel="noopener noreferrer"><AiFillInstagram/></a>


          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-20 overflow-hidden md:h-96 md:w-96">

          <Image src={avatar} layout="fill" objectFit="cover"/>

          </div>
        </section>

        <section>
          <div className="pt-12">
          <h3 className="text-3xl py-1 text-gray-800 dark:text-white">About Me</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I am a multidisciplinary digital creator with skills in front-end development, graphic design, and photography. By combining technical implementation, visual design, and composition, I build interfaces and visuals that are both functional and aesthetically strong.</p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Focused on modern UI, visual clarity, and responsive web experiences.</p>
          </div>

            <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">

            <Image src={design} width={100} height={100} className="mx-auto" />
            <h3 className="text-black text-lg font-medium pt-8 pb-2">Graphic Design</h3>
            <p className="text-gray-600 py-2">I create visual assets and UI layouts with attention to typography, color harmony, and visual consistency.</p>
            <h4 className="py-4 text-teal-600">Design Skills</h4>
            <p className="text-gray-800 py-1">Adobe Photoshop</p>
            <p className="text-gray-800 py-1">Adobe Illustrator</p>
            <p className="text-gray-800 py-1">Canva</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">

            <Image src={code} width={100} height={100} className="mx-auto" />
            <h3 className="text-black text-lg font-medium pt-8 pb-2">Front-End Development</h3>
            <p className="text-gray-600 py-2">I focus on building responsive, clean, and maintainable user interfaces using modern web technologies.</p>
            <h4 className="py-4 text-teal-600">Skills</h4>
            <p className="text-gray-800 py-1">HTML</p>
            <p className="text-gray-800 py-1">CSS</p>
            <p className="text-gray-800 py-1">JavaScript</p>
            <p className="text-gray-800 py-1">React JS & Next JS</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={camera} width={100} height={100} className="mx-auto" />
            <h3 className="text-black text-lg font-medium pt-8 pb-2">Photography</h3>
            <p className="text-gray-600 py-2">I work with photography as a visual medium to capture mood, composition, and storytelling, supporting creative and digital projects.</p>
            <h4 className="py-4 text-teal-600">Focus Areas</h4>
            <p className="text-gray-800 py-1">Composition</p>
            <p className="text-gray-800 py-1">Color Grading</p>
            <p className="text-gray-800 py-1">Photo Editing</p>

            </div>

            </div>        
        </section>

        <section>

        <div>

        <h3 className="text-3xl py-1 text-gray-800 dark:text-white">Front End Developer · Graphic Designer · Photographer</h3>
        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I create clean, functional, and visually compelling digital experiences by combining code, design, and visual storytelling.</p>
        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Focused on modern UI, visual clarity, and responsive web experiences.</p>

        </div>

        <h3 className="text-black text-3xl text-center py-1 dark:text-white"  id="projects">Web Projects</h3>

        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

        <div className="basis-1/3 flex-1">

        <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>

        </div>

        <div className="basis-1/3 flex-1">

        <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>

        </div>

        <div className="basis-1/3 flex-1">

        <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>

        </div>

        <div className="basis-1/3 flex-1">

        <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>

        </div>

        </div>

        </section>

      </main>
    </div>
  )
}
